sudo: required
services:
        - docker

before_install:
        - docker build -t nikosnicolaides/docker-test -f Dockerfile.dev .

script:
        - docker run nikosnicolaides/docker-test npm run test -- --coverage

